#--------------------------------------------------------------------------------
# Generated by Ansible (# /Users/oonisim/Home/Study/Computing/04.Technologies/GA/Spark/Apache-Spark-Installation/installation/ansible/aws/operations/plays/roles/list/templates/spark/workers.j2)
#--------------------------------------------------------------------------------
SPARK_WORKERS='ip-10-0-0-153.us-west-1.compute.internal'
SPARK_MASTER_HOSTNAME=ip-10-0-0-148.us-west-1.compute.internal
SPARK_MASTER_IP=10.0.0.148
