- name: "Overwrite {{ HADOOP_HOME }}/etc/"
  copy:
    src   : "{{ role_path }}/files/{{ item }}"
    dest  : "{{ HADOOP_HOME }}/etc/{{ item }}"
    owner : "{{ HADOOP_ADMIN }}"
    group : "{{ HADOOP_GROUP }}"
    mode  : 0664
    backup: yes
  with_fileglob:
    - {{ role_path }}/files/*

- name: "Format file system"
  become: true
  become_user: "{{ HADOOP_ADMIN }}"
  shell: |
    {{ HADOOP_HOME }}/sbin/stop-dfs.sh
    {{ HADOOP_HOME }}/bin/dfs namenode -format