- name: "Overwrite {{ HADOOP_HOME }}/etc/"
  copy:
    src   : "{{ role_path }}/files/{{ item }}"
    dest  : "{{ HADOOP_HOME }}/etc/{{ item }}"
    owner : "{{ HADOOP_ADMIN }}"
    group : "{{ HADOOP_GROUP }}"
    mode  : 0664
    backup: yes
  with_fileglob:
    - {{ role_path }}/files/*

- name: "Start cluster"
  become: true
  become_user: "{{ HADOOP_ADMIN }}"
  shell: |
    export JAVA_HOME="$(jrunscript -e 'java.lang.System.out.println(java.lang.System.getProperty("java.home"));')"
    {{HADOOP_HOME}}/sbin/start-dfs.sh