#--------------------------------------------------------------------------------
# Local hadoop manifest folder
# Hadoop module is responsible to provide the hadoop cluster information e.g.
# hadoop Name node hostname/IP, hadoop configuration files, etc, so that 
# services e.g. Spark module can use those information to configure.
# 
# Those information is store in files under the manifest holder.
#--------------------------------------------------------------------------------
HADOOP_ARTEFACT_DIR: "{{ lookup('env','INSTALL_HOME') }}//artefacts/hadoop"

#--------------------------------------------------------------------------------
# Hadoop installation package
#--------------------------------------------------------------------------------
HADOOP_VERSION: 2.8.4
HADOOP_PACKAGE: "hadoop-{{ HADOOP_VERSION }}.tar.gz"
HADOOP_DOWNLOAD_URL: "http://apache.mirror.amaze.com.au/hadoop/common/hadoop-{{ HADOOP_VERSION }}/{{ HADOOP_PACKAGE }}"
HADOOP_PACKAGE_CHECKSUM: "md5:B30B409BB69185003B3BABD1504BA224"
HADOOP_DOWNLOAD_DIR: "~{{ HADOOP_ADMIN }}/downloads"

#--------------------------------------------------------------------------------
# Administration account
#--------------------------------------------------------------------------------
HADOOP_ADMIN : hadoop
HADOOP_GROUP: hadoop

#--------------------------------------------------------------------------------
# Home
#--------------------------------------------------------------------------------
HADOOP_HOME: "/usr/local/hadoop"
HADOOP_CONF_DIR: "{{ HADOOP_HOME }}/etc/hadoop"

#--------------------------------------------------------------------------------
# Core
# https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/core-default.xml
#--------------------------------------------------------------------------------
# hadoop.tmp.dir
HADOOP_CORE_TMP_DIR: "/tmp/hadoop-{{ HADOOP_ADMIN }}"

#--------------------------------------------------------------------------------
# Name Node configurations
#--------------------------------------------------------------------------------
# fs.defaultFS
HADOOP_NN_HOSTNAME: "{{ lookup('env','HADOOP_NN_HOSTNAME') }}"
HADOOP_NN_PORT: 8020
HADOOP_WORKERS: "{{ lookup('env','HADOOP_WORKERS') }}" 

#--------------------------------------------------------------------------------
# HDFS configurations
# https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/hdfs-default.xml
#--------------------------------------------------------------------------------
HADOOP_DFS_REPLICATION: 1
HADOOP_DFS_BLOCK_SIZE: 134217728

# dfs.datanode.data.dir
HADOOP_DFS_DATA_DIR: "/home/{{ HADOOP_ADMIN }}/dfs/data"

#--------------------------------------------------------------------------------
# YARN configurations
#--------------------------------------------------------------------------------
# yarn.resourcemanager.hostname<
YARN_RM_HOSTNAME:  "{{ lookup('env','YARN_RM_HOSTNAME') }}"
# yarn.nodemanager.resource.cpu-vcores
YARN_NM_CPU_VCORES: 2
# yarn.nodemanager.resource.memory-mb
YARN_NM_MEMORY_MB: 2048
# yarn.nodemanager.aux-services
YARN_NM_AUX_SERVICES: mapreduce_shuffle
# yarn.nodemanager.aux-services.mapreduce_shuffle.class
YARN_NM_AUX_SERVICES_SHUFFLE_CLASS: org.apache.hadoop.mapred.ShuffleHandler