#-------------------------------------------------------------------------------
# Environment common/defaults.
# Override with environment specifics in an inventory directory files.
#-------------------------------------------------------------------------------
ENV_ID: aws
