- name: Setup for master
  hosts: masters
  any_errors_fatal: true
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - site.common
    - site.java
    - site.sbt    # Required to compile application programs, e.g. naive bayes.

