- name: "Overwrite {{ HADOOP_HOME }}/etc/"
  copy:
    src   : "{{ item }}"
    dest  : "{{ HADOOP_HOME }}/etc/{{ item }}"
    owner : "{{ HADOOP_ADMIN }}"
    group : "{{ HADOOP_GROUP }}"
    mode  : 0664
    backup: yes
  with_fileglob:
    "- {{ role_path }}/files/hadoop/*"
