- name: "Overwrite {{ HADOOP_CONF_HOME }}"
  copy:
    src   : "{{ item }}"
    dest  : "{{ HADOOP_CONF_HOME }}/{{ item | basename }}"
    owner : "{{ HADOOP_ADMIN }}"
    group : "{{ HADOOP_GROUP }}"
    mode  : 0664
    backup: yes
  with_fileglob:
    - "{{ role_path }}/files/hadoop/*"
