- name: "Start HDFS"
  become: true
  become_user: "{{ HADOOP_ADMIN }}"
  shell: |
    {{ HADOOP_HOME }}/sbin/start-dfs.sh
  environment: 
    JAVA_HOME: "{{ java_home.stdout }}"
    HADOOP_HOME: "{{ HADOOP_HOME }}"

# Starting YARN from within ansible with "shell" seems to fail.
# It was working before with ansible 2.9.x, but may start fail with 2.11.x.
# The workaround is using nohup.
# https://stackoverflow.com/questions/66295332
- name: "Start YARN"
  become: true
  become_user: "{{ HADOOP_ADMIN }}"
  shell: |
    nohup {{ HADOOP_HOME }}/sbin/start-yarn.sh &
  environment: 
    JAVA_HOME: "{{ java_home.stdout }}"
    HADOOP_HOME: "{{ HADOOP_HOME }}"

- name: "Wait cluster running"
  shell: |
    pgrep -a java | grep 'file=hadoop-policy.xml'
  register: _result
  until: _result.rc == 0
  retries: 5
  delay: 30
  ignore_errors: true

- name: "Verify HDFS"
  become: true
  become_user: "{{ HADOOP_ADMIN }}"
  shell: |
    {{ HADOOP_HOME }}/bin/hdfs dfsadmin -report
    {{ HADOOP_HOME }}/bin/hadoop classpath
  environment: 
    JAVA_HOME: "{{ java_home.stdout }}"
    HADOOP_HOME: "{{ HADOOP_HOME }}"

- name: "Create /tmp with owner {{ HADOOP_ADMIN }}:{{ HADOOP_GROUP }}."
  become: true
  become_user: "{{ HADOOP_ADMIN }}"
  shell: |
    {{ HADOOP_HOME }}/bin/hadoop fs -mkdir -p /tmp
    {{ HADOOP_HOME }}/bin/hadoop fs -chmod 1777 /tmp
    {{ HADOOP_HOME }}/bin/hadoop fs -chown {{ HADOOP_ADMIN }}:{{ HADOOP_GROUP }} /tmp
  environment:
    JAVA_HOME: "{{ java_home.stdout }}"
    HADOOP_HOME: "{{ HADOOP_HOME }}"

#- name: "Pause for 2 minutes to wait YARN to startup."
#  pause:
#    minutes: 1

- name: check if YARN is running
  command: curl -sf http://{{ HADOOP_RM_HOSTNAME }}:{{ HADOOP_RM_PORT }}

