#--------------------------------------------------------------------------------
# Generated by Ansible (# /Users/oonisim/Home/Study/Computing/04.Technologies/GA/Spark/Apache-Spark-Installation/installation/ansible/aws/operations/plays/roles/list/templates/spark/env.sh.j2)
#--------------------------------------------------------------------------------
HADOOP_WORKERS='ip-10-0-0-153.us-west-1.compute.internal'
HADOOP_NN_HOSTNAME='ip-10-0-0-148.us-west-1.compute.internal'
YARN_RM_HOSTNAME='ip-10-0-0-148.us-west-1.compute.internal'
