- name: "Identify JAVA_HOME"
  import_tasks: env.yml

# Create event log directory in HDFS.
- name: "Place {{ _filename.stdout }} in HDFS"
  become: true
  become_user: "{{ HADOOP_ADMIN }}"
  # The first line is a header    
  shell: | 
    hdfs dfs -mkdir -p {{ SPARK_LOG_DIR }}
    hdfs dfs -chown -R {{ SPARK_ADMIN }} {{ SPARK_LOG_DIR }}
  environment: 
    PATH: "{{ ansible_env.PATH }}:{{ HADOOP_HOME }}/bin:{{ SPARK_HOME }}:/bin"
    JAVA_HOME: "{{ java_home.stdout }}"    

- name: "Start cluster"
  become: true
  become_user: "{{ SPARK_ADMIN }}"
  shell: |
    {{ SPARK_HOME }}/sbin/start-all.sh
    {{ SPARK_HOME }}/sbin/start-history-server.sh
  environment: 
    JAVA_HOME: "{{ java_home.stdout }}"    
        
