- import_tasks: env.yml
- import_tasks: hadoop.yml

- name: "Start cluster"
  become: true
  become_user: "{{ SPARK_ADMIN }}"
  shell: |
    {{ SPARK_HOME }}/sbin/start-all.sh
  environment: 
    JAVA_HOME: "{{ java_home.stdout }}"    
        
- name: "Start history server"
  become: true
  become_user: "{{ SPARK_ADMIN }}"
  shell: |
    echo "https://stackoverflow.com/questions/38350249"
    mkdir -p /tmp/spark-events
    {{ SPARK_HOME }}/sbin/start-history-server.sh
  environment: 
    JAVA_HOME: "{{ java_home.stdout }}"    

