- name: "mkdir {{ _APP_BUILD_DIR }}"
  file:
    path:   "{{ _APP_BUILD_DIR }}"
    state:  directory
    owner:  "{{ HADOOP_ADMIN }}"
    group:  "{{ HADOOP_GROUP }}"
    mode:   0770
    recurse: true

- name: "Copy package"
  copy: 
    src: "{{ item }}"
    dest: "{{ _APP_BUILD_DIR }}"
    owner:  "{{ HADOOP_ADMIN }}"
    group:  "{{ HADOOP_GROUP }}"
    mode:   0660
  with_fileglob:
    - "scala/*"

- name: "Build scala/spark executable"
  become: true
  become_user: "{{ HADOOP_ADMIN }}"
  shell: |
    sbt clean
    sbt compile
    sbt package
  args:
    chdir: "{{ _APP_BUILD_DIR }}"
