- name: "Copy package"
  template: 
    src: "{{ item }}"
    dest: "{{ _APP_BUILD_DIR }}/{{ item | basename }}"
    owner:  "{{ SPARK_ADMIN }}"
    group:  "{{ SPARK_GROUP }}"
    mode:   0660
  with_fileglob:
    - "{{ role_path }}/templates/scala/*"

- name: "Build scala/spark executable"
  become: true
  become_user: "{{ SPARK_ADMIN }}"
  shell: |
    sbt clean
    sbt compile
    sbt package
  args:
    chdir: "{{ _APP_BUILD_DIR }}"
