- name: "Create {{ _APP_DIR }}"
  file:
    path:   "{{ _APP_DIR }}"
    state:  directory
    owner:  "{{ SPARK_ADMIN }}"
    group:  "{{ HADOOP_GROUP }}"
    mode:   0770
    recurse: true

- name: "mkdir {{ _APP_DATA_DIR }}"
  file:
    path:   "{{ _APP_DATA_DIR }}"
    state:  directory
    owner:  "{{ SPARK_ADMIN }}"
    group:  "{{ HADOOP_GROUP }}"
    mode:   0770
    recurse: true
    
- name: "mkdir {{ _APP_BUILD_DIR }}"
  file:
    path:   "{{ _APP_BUILD_DIR }}"
    state:  directory
    owner:  "{{ SPARK_ADMIN }}"
    group:  "{{ SPARK_GROUP }}"
    mode:   0770
    recurse: true

#--------------------------------------------------------------------------------
# HDFS directory to store data to process
#--------------------------------------------------------------------------------
- name: "Create {{ _APP_HDFS_DIR }} in HDFS"
  become: true
  become_user: "{{ HADOOP_ADMIN }}"
  shell: | 
    hdfs dfs -mkdir -p {{ _APP_HDFS_DIR }}
  environment: 
    PATH: "{{ ansible_env.PATH }}:{{ HADOOP_HOME }}/bin:{{ SPARK_HOME }}:/bin"
    JAVA_HOME: "{{ java_home.stdout }}"    
