#--------------------------------------------------------------------------------
# Generated by Ansible (# /Users/oonisim/Home/Study/Computing/04.Technologies/GA/Spark/Apache-Spark-Installation/installation/ansible/aws/operations/plays/roles/list/templates/spark/workers.j2)
#--------------------------------------------------------------------------------
SPARK_WORKERS='localhost'
SPARK_MASTER_HOSTNAME=localhost
SPARK_MASTER_IP=127.0.0.1
