#--------------------------------------------------------------------------------
# Clean up previous installations
#--------------------------------------------------------------------------------
- name: "Stop cluster"
  shell: |
    {{HADOOP_HOME}}/sbin/stop-dfs.sh
  become: true
  become_user: "{{ HADOOP_ADMIN }}"
  ignore_errors: true

- name: "Remove {{ HADOOP_PACKAGE }}"
  shell: |
    rm {{ HADOOP_PACKAGE }}
  args:
    chdir: "{{ HADOOP_DOWNLOAD_DIR }}"
  ignore_errors: true

- name: Delete HADOOP envirinment variables
  file:
    path: /etc/profile.d/hadoop.sh
    state: absent
  ignore_errors: true

- name: "Delete {{ HADOOP_HOME }}"
  file:
    path: "{{ HADOOP_HOME }}"
    state: absent
  ignore_errors: true
    
#--------------------------------------------------------------------------------
# Install Packages
#--------------------------------------------------------------------------------
- include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_major_version}}.yml"
- include: "{{ ansible_distribution }}_{{ ansible_distribution_major_version}}.yml"

- name: "Create/recreate {{ HADOOP_DOWNLOAD_DIR }}"
  file:
    path:   "{{ HADOOP_DOWNLOAD_DIR }}"
    state:  "directory"
    owner:  "{{ HADOOP_ADMIN }}"
    group:  "{{ HADOOP_GROUP }}"
    mode:   0770

- name: "Set owner/group as {{ HADOOP_ADMIN }}:{{ HADOOP_GROUP }} recursively {{ HADOOP_HOME }}"
  file:
    path:   "{{ HADOOP_HOME }}"
    state:  "directory"
    owner:  "{{ HADOOP_ADMIN }}"
    group:  "{{ HADOOP_GROUP }}"
    recurse: true

- name: "Download {{ HADOOP_DOWNLOAD_URL }}"
  get_url:
    url:   "{{ HADOOP_DOWNLOAD_URL }}"
    dest:  "{{ HADOOP_DOWNLOAD_DIR }}/{{ HADOOP_PACKAGE }}"
    owner: "{{ HADOOP_ADMIN }}"
    group: "{{ HADOOP_GROUP }}"
    mode:  0770
    checksum: "{{ HADOOP_PACKAGE_CHECKSUM }}"

- name: "Install {{ HADOOP_PACKAGE }}"
  shell: |
    tar --overwrite --owner={{ HADOOP_ADMIN }} --group={{ HADOOP_GROUP }} -xzvf {{ HADOOP_PACKAGE }} -C {{ HADOOP_HOME }} --strip-components=1
  args:
    chdir: "{{ HADOOP_DOWNLOAD_DIR }}"

# Environment setup.
- name: Set HADOOP envirinment variables
  template:
    src: hadoop.sh.j2
    dest: /etc/profile.d/hadoop.sh
    mode: 0644
