#--------------------------------------------------------------------------------
# Clean up previous installations
#--------------------------------------------------------------------------------
- name: "Stop cluster"
  shell: |
    {{HADOOP_HOME}}/sbin/stop-dfs.sh
  become: true
  become_user: "{{ HADOOP_ADMIN }}"
  ignore_errors: true

- name: "Delete hadoop directories"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ HADOOP_DOWNLOAD_DIR }}"
    - "{{ HADOOP_HOME }} "
    - "{{ HADOOP_CORE_TMP_DIR }}"
    - "{{ HADOOP_DFS_DATA_DIR }}"
  ignore_errors: true

- name: Delete HADOOP environment variable setups
  file:
    path: /etc/profile.d/hadoop.sh
    state: absent
  ignore_errors: true
    
#--------------------------------------------------------------------------------
# Download package and install
#--------------------------------------------------------------------------------
- name: "Create hadoop directories"
  file:
    path:   "{{ item }}"
    state:  directory
    owner:  "{{ HADOOP_ADMIN }}"
    group:  "{{ HADOOP_GROUP }}"
    mode:   0770
    recurse: true
  with_items:
    - "{{ HADOOP_DOWNLOAD_DIR }}"
    - "{{ HADOOP_HOME }}"
    - "{{ HADOOP_CORE_TMP_DIR }}"
    - "{{ HADOOP_DFS_DATA_DIR }}"


- name: "Download {{ HADOOP_DOWNLOAD_URL }}"
  get_url:
    url:      "{{ HADOOP_DOWNLOAD_URL }}"
    checksum: "{{ HADOOP_PACKAGE_CHECKSUM }}"
    dest:     "{{ HADOOP_DOWNLOAD_DIR }}/{{ HADOOP_PACKAGE }}"
    owner:    "{{ HADOOP_ADMIN }}"
    group:    "{{ HADOOP_GROUP }}"
    mode:     0770

- name: "Install {{ HADOOP_PACKAGE }}"
  shell: |
    tar --overwrite --owner={{ HADOOP_ADMIN }} --group={{ HADOOP_GROUP }} -xzvf {{ HADOOP_PACKAGE }} -C {{ HADOOP_HOME }} --strip-components=1
  args:
    chdir: "{{ HADOOP_DOWNLOAD_DIR }}"

- name: Place /etc/profile.d/hadoop.sh
  template:
    src: hadoop.sh.j2
    dest: /etc/profile.d/hadoop.sh
    mode: 0644
