#--------------------------------------------------------------------------------
# Format HDFS
# -force is required as it wait for stdin input, and returns 257.
#--------------------------------------------------------------------------------
- name: "Clear data directory before format"
  become: true
  become_user: "{{ HADOOP_ADMIN }}"
  shell: |
    for host in $(cat {{ HADOOP_HOME }}/etc/hadoop/slaves | grep -v '^#')
    do
      ssh -oStrictHostKeyChecking=no $host rm -rf {{ HADOOP_DFS_DATA_DIR }}
    done
  args:
    executable: /bin/bash

- name: "Format file system"
  become: true
  become_user: "{{ HADOOP_ADMIN }}"
  shell: |
    {{ HADOOP_HOME }}/bin/hdfs namenode -format -force
  run_once: yes
  environment: 
    JAVA_HOME: "{{ java_home.stdout }}"    
