#--------------------------------------------------------------------------------
# Disable Firewalld (K8S uses iptables)
#--------------------------------------------------------------------------------
- service:
    name: ufw
    state: stopped
    enabled: no
  ignore_errors: true