#--------------------------------------------------------------------------------
# kube-proxy utilizes iptables to control the pod network traffic.
# - kubernetes.io/docs/concepts/cluster-administration/network-plugins/
# - https://wiki.libvirt.org/page/Net.bridge.bridge-nf-call_and_sysctl.conf
#--------------------------------------------------------------------------------

# Need to change to correctly set ulimits. Below seems not working
# Need to change to correctly set ulimits. Below seems not working
- name: "ulimit for {{ HADOOP_ADMIN }}"
  shell:
    cmd: |
      sudo tee /etc/sysctl.d/hdfs.conf <<EOF
      @{{ HADOOP_ADMIN | quote }}          soft    nofile          10000
      @{{ HADOOP_ADMIN | quote }}          hard    nofile          10000
      EOF

- name: "ulimit for {{ SPARK_ADMIN }}"
  shell:
    cmd: |
      sudo tee /etc/sysctl.d/hdfs.conf <<EOF
      @{{ SPARK_ADMIN | quote }}           soft    nofile          10000
      @{{ SPARK_ADMIN | quote }}           hard    nofile          10000
      @{{ SPARK_ADMIN | quote }}           soft    nproc           8096
      @{{ SPARK_ADMIN | quote }}           hard    nofile          8096
      EOF

- name: Reload sysctl
  shell: |
    sysctl --system
    sudo sysctl -a
