#--------------------------------------------------------------------------------
# Clean up previous installations
#--------------------------------------------------------------------------------


#--------------------------------------------------------------------------------
# Install Pckages
#--------------------------------------------------------------------------------
#- name: Install sbt
#  shell: |
#    curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo

- name: "Setup SBT yum repository"
  get_url:
    url:   "https://bintray.com/sbt/rpm/rpm"
    dest:  "/etc/yum.repos.d/bintray-sbt-rpm.repo"

- name: "Install sbt packages"
  yum:
    name: "sbt"
    update_cache: "true"
    state: latest


