#--------------------------------------------------------------------------------
# kube-proxy utilizes iptables to control the pod network traffic.
# - kubernetes.io/docs/concepts/cluster-administration/network-plugins/
# - https://wiki.libvirt.org/page/Net.bridge.bridge-nf-call_and_sysctl.conf
#--------------------------------------------------------------------------------

# Need to change to correctly set ulimits. Below seems not working
# Need to change to correctly set ulimits. Below seems not working
- name: "Enable pod network traffic procssing in iptables."
  shell:
    cmd: |
      sudo tee /etc/sysctl.d/hdfs.conf <<EOF
      soft nofile 8192
      hard nofile 8192
      EOF

- name: Reload sysctl
  shell: |
    sysctl --system
    sudo sysctl -a
