---
- name: create hadoop configuration files...
  template:
    src:    "{{ item }}"
    dest:   "{{ HADOOP_OUTPUT_DIR }}/{{ item | basename | regex_replace('\\j2','') }}"
  with_fileglob:
    - "{{ role_path }}/templates/hadoop/*"

- name: create spark configuration files...
  template:
    src:    "{{ item }}"
    dest:   "{{ SPARK_OUTPUT_DIR }}/{{ item | basename | regex_replace('\\.j2','') }}"
  with_fileglob:
    - "{{ role_path}}/templates/spark/*.j2"

- name: create hosts file for /etc/hosts ...
  local_action:
    module: template
    src:    hosts.j2
    dest:   "{{ OS_OUTPUT_DIR }}/hosts"
