HADOOP_USERS:
  - name: "{{ HADOOP_ADMIN }}"
    group: "{{ HADOOP_GROUP }}"
    groups: "{{ SPARK_GROUP }}"
    ssh_private_key: "~/.ssh/id_rsa"
    ssh_authorized_keys:
      - "~/.ssh/id_rsa.pub"
    password: "$6$hST4tQuv$0bS1cMCO1kyC4ztDr6uh3zPE33eeGf2mEFClDlhpP9UvCbnZ3Cu12AxnCLT2FGnOw0k4YCSQvtKRwtJHkj642."

  - name: "{{ SPARK_ADMIN }}"
    group: "{{ SPARK_GROUP }}"
    groups: "{{ HADOOP_GROUP }}"
    ssh_private_key: "~/.ssh/id_rsa"
    ssh_authorized_keys:
      - "~/.ssh/id_rsa.pub"
    password: "$6$hST4tQuv$0bS1cMCO1kyC4ztDr6uh3zPE33eeGf2mEFClDlhpP9UvCbnZ3Cu12AxnCLT2FGnOw0k4YCSQvtKRwtJHkj642."


#--------------------------------------------------------------------------------
# Constants
#--------------------------------------------------------------------------------
NODE_TYPE_MASTER: "master"
NODE_TYPE_WORKER: "worker"

#--------------------------------------------------------------------------------
# [Security]
#--------------------------------------------------------------------------------
DECRYPT_KEY_FILE: "~/.ssh/private.pem"

#--------------------------------------------------------------------------------
# Docker
#--------------------------------------------------------------------------------
DOCKER_GROUP: "docker"
DOCKER_USERS:
  - "{{ SPARK_ADMIN }}"

